// packages/solid/src/headless.ts
import { createEffect, createSignal, onCleanup, untrack } from 'solid-js'
import type { Accessor } from 'solid-js'
import type { DepositController, Snapshot } from '@openrampkit/client'

type MaybeAccessor<T> = T | Accessor<T>

/**
 * Subscribe to a `DepositController` and return its snapshot as an accessor. For fully custom UIs.
 * `controller` can be a value or an accessor. The snapshot is `undefined` while there is no controller.
 */
export function useDepositController(controller: MaybeAccessor<DepositController | undefined | null>): Accessor<Snapshot | undefined> {
  const get = typeof controller === 'function' ? controller : () => controller
  const [snap, setSnap] = createSignal<Snapshot | undefined>(untrack(get)?.getSnapshot())
  // Effects do not run during server rendering, so nothing subscribes there.
  createEffect(() => {
    const c = get()
    setSnap(() => c?.getSnapshot())
    if (c) onCleanup(c.subscribe(() => setSnap(() => c.getSnapshot())))
  })
  return snap
}

// packages/react/src/headless.ts
import { useSyncExternalStore } from 'react'
import type { DepositController, Snapshot } from '@openrampkit/client'

const noopSubscribe = () => () => {}
const none = () => undefined

/** Subscribe to a `DepositController` and return its snapshot. For fully custom UIs. */
export function useDepositController(controller: DepositController): Snapshot
export function useDepositController(controller: DepositController | undefined | null): Snapshot | undefined
export function useDepositController(controller: DepositController | undefined | null): Snapshot | undefined {
  return useSyncExternalStore(
    controller ? controller.subscribe : noopSubscribe,
    controller ? controller.getSnapshot : none,
    controller ? controller.getSnapshot : none,
  )
}
