// packages/react/src/provider.ts
import { createContext, createElement, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import type { OrkEvent, PublicSession, WalletAdapter } from '@openrampkit/core'
import type { Appearance, Theme } from '@openrampkit/web/theme'
import type { DepositHandle, Messages } from '@openrampkit/web'
import { loadWeb } from './load.js'

export type OpenRampProviderProps = {
  /** Base URL of your OpenRampKit server handler, e.g. `/api/openramp` */
  baseUrl: string
  wallet?: WalletAdapter
  theme?: Theme
  appearance?: Appearance
  /** Partial message catalog. Overrides the locale catalog key by key. */
  messages?: Partial<Messages>
  /** BCP 47 locale (`en`, `vi`, `id`, `th`, `ms`, `fil`, ...). Default: session locale, then browser language, then English. */
  locale?: string
  onEvent?: (e: OrkEvent) => void
  children?: ReactNode
}

export type BeginDepositOptions = {
  clientSecret: string | (() => Promise<string>)
  onEvent?: (e: OrkEvent) => void
}

export type BeginWithdrawOptions = BeginDepositOptions

export type OpenRampApi = {
  /** Opens the modal. Resolves with the session when the deposit completes; rejects if the modal closes first. */
  beginDeposit(opts: BeginDepositOptions): Promise<PublicSession>
  /**
   * Opens the modal for a withdraw session (created on your server with `direction: 'withdraw'`).
   * Resolves with the session when the withdrawal completes; rejects if the modal closes first.
   */
  beginWithdraw(opts: BeginWithdrawOptions): Promise<PublicSession>
  close(): void
  isOpen: boolean
}

type Ctx = OpenRampApi & Omit<OpenRampProviderProps, 'children'>

const OpenRampContext = createContext<Ctx | null>(null)

export function OpenRampProvider(props: OpenRampProviderProps) {
  const { children, ...config } = props
  const configRef = useRef(config)
  configRef.current = config
  const handleRef = useRef<DepositHandle | null>(null)
  const [isOpen, setOpen] = useState(false)

  const close = useCallback(() => {
    handleRef.current?.close()
    handleRef.current = null
  }, [])

  const begin = useCallback(async (kind: 'deposit' | 'withdraw', opts: BeginDepositOptions): Promise<PublicSession> => {
    const web = await loadWeb()
    handleRef.current?.close()
    const c = configRef.current
    const onEvent = (e: OrkEvent) => {
      c.onEvent?.(e)
      opts.onEvent?.(e)
    }
    const handle = (kind === 'withdraw' ? web.openWithdraw : web.openDeposit)({
      baseUrl: c.baseUrl,
      clientSecret: opts.clientSecret,
      onEvent,
      onClose: () => {
        if (handleRef.current === handle) handleRef.current = null
        setOpen(false)
      },
      ...(c.wallet ? { wallet: c.wallet } : {}),
      ...(c.theme ? { theme: c.theme } : {}),
      ...(c.appearance ? { appearance: c.appearance } : {}),
      ...(c.messages ? { messages: c.messages } : {}),
      ...(c.locale ? { locale: c.locale } : {}),
    })
    handleRef.current = handle
    setOpen(true)
    return handle.done
  }, [])
  const beginDeposit = useCallback((opts: BeginDepositOptions) => begin('deposit', opts), [begin])
  const beginWithdraw = useCallback((opts: BeginWithdrawOptions) => begin('withdraw', opts), [begin])

  // Close the modal when the provider unmounts.
  useEffect(() => () => handleRef.current?.close(), [])

  // Keep theme changes live while the modal is open.
  useEffect(() => {
    const el = handleRef.current?.element
    if (!el) return
    el.theme = config.theme
    el.appearance = config.appearance
    el.locale = config.locale
  }, [config.theme, config.appearance, config.locale, isOpen])

  const value = useMemo<Ctx>(() => ({ ...config, beginDeposit, beginWithdraw, close, isOpen }), [config.baseUrl, config.wallet, config.theme, config.appearance, config.messages, config.locale, config.onEvent, beginDeposit, beginWithdraw, close, isOpen])
  return createElement(OpenRampContext.Provider, { value }, children)
}

function useCtx(): Ctx {
  const ctx = useContext(OpenRampContext)
  if (!ctx) throw new Error('@openrampkit/react: wrap your app in <OpenRampProvider>.')
  return ctx
}

/** `{ beginDeposit, beginWithdraw, close, isOpen }` */
export function useOpenRamp(): OpenRampApi {
  const { beginDeposit, beginWithdraw, close, isOpen } = useCtx()
  return { beginDeposit, beginWithdraw, close, isOpen }
}

/** Provider config, or null outside a provider. Internal. */
export function useOpenRampConfig(): Ctx | null {
  return useContext(OpenRampContext)
}

// packages/solid/src/provider.ts
import { createComponent, createContext, createEffect, createSignal, on, onCleanup, useContext } from 'solid-js'
import type { Accessor, JSX } from 'solid-js'
import type { PublicSession } from '@openrampkit/core'
import { createRampCore } from './ramp.js'
import type { BeginDepositOptions, BeginWithdrawOptions, OpenRampConfig } from './ramp.js'

export type OpenRampProviderProps = OpenRampConfig & { children?: JSX.Element }

export type OpenRampApi = {
  /** Opens the modal. Resolves with the session when the deposit completes; rejects if the modal closes first. */
  beginDeposit(opts: BeginDepositOptions): Promise<PublicSession>
  /**
   * Opens the modal for a withdraw session (created on your server with `direction: 'withdraw'`).
   * Resolves with the session when the withdrawal completes; rejects if the modal closes first.
   */
  beginWithdraw(opts: BeginWithdrawOptions): Promise<PublicSession>
  close(): void
  /** Whether the modal is open */
  isOpen: Accessor<boolean>
}

type Ctx = { api: OpenRampApi; config: () => OpenRampConfig }

const OpenRampContext = createContext<Ctx>()

/** Holds the shared config and opens the modal. Theme, appearance and locale changes reach an open modal. */
export function OpenRampProvider(props: OpenRampProviderProps): JSX.Element {
  const [isOpen, setOpen] = createSignal(false)
  const config = (): OpenRampConfig => {
    const c: OpenRampConfig = { baseUrl: props.baseUrl }
    if (props.wallet) c.wallet = props.wallet
    if (props.theme) c.theme = props.theme
    if (props.appearance) c.appearance = props.appearance
    if (props.messages) c.messages = props.messages
    if (props.locale) c.locale = props.locale
    if (props.providerRenderers) c.providerRenderers = props.providerRenderers
    if (props.onEvent) c.onEvent = props.onEvent
    return c
  }
  const core = createRampCore(config, (v) => setOpen(v))
  createEffect(on(() => [props.theme, props.appearance, props.locale], () => core.sync(), { defer: true }))
  // Close the modal when the provider unmounts.
  onCleanup(() => core.close())
  const api: OpenRampApi = { beginDeposit: core.beginDeposit, beginWithdraw: core.beginWithdraw, close: core.close, isOpen }
  return createComponent(OpenRampContext.Provider, {
    value: { api, config },
    get children() {
      return props.children
    },
  })
}

/** `{ beginDeposit, beginWithdraw, close, isOpen }`. Throws outside `<OpenRampProvider>`. */
export function useOpenRamp(): OpenRampApi {
  const ctx = useContext(OpenRampContext)
  if (!ctx) throw new Error('@openrampkit/solid: wrap your app in <OpenRampProvider>.')
  return ctx.api
}

/** Provider config, or undefined outside a provider. Internal. */
export function useOpenRampConfig(): (() => OpenRampConfig) | undefined {
  return useContext(OpenRampContext)?.config
}
